language: android
jdk: oraclejdk8
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "pushd /tmp"
 - "git clone https://github.com/secure-software-engineering/DroidBench.git"
 - "popd"
 - "mkdir -p $TRAVIS_BUILD_DIR/com.ibm.wala.dalvik.test/lib"
 - "find /usr/local -name dx.jar -exec cp '{}' $TRAVIS_BUILD_DIR/com.ibm.wala.dalvik.test/lib/dx.jar ';'"
install: mvn clean verify -DskipTests=true -B -q
script: mvn clean verify -B -q
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib
    